### ISSUE TITLE
Add main.nf from module test as example of module usage for each module.

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/website#1028]
**Is your feature request related to a problem? Please describe.**
Sometimes the community asks how to use a module. 

**Describe the solution you'd like**
Each module page has an "Example usage:" section. One suggestion is to take the `main.nf` from `tests/modules/MODULE/main.nf` and display it as code block.

e.g. The tool Abacus: https://nf-co.re/modules/abacas
Would include:

## Example Usage:
```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

include { ABACAS } from '../../../modules/abacas/main.nf'

workflow test_abacas {

    input = [ [ id:'test', single_end:false ], // meta map
              file(params.test_data['sarscov2']['illumina']['scaffolds_fasta'], checkIfExists: true)
            ]

    fasta = file(params.test_data['sarscov2']['genome']['genome_fasta'], checkIfExists: true)

    ABACAS ( input, fasta )
}
```

**Comment by Emiller88** [comment]
I've been thinking about something similar, but I think we could just pull in the tests. I think we should also expand the usage examples in the tests, though, with patterns included:

```nextflow
bam = normal_meta_bam_ch
ch_genomecov_bam = bam.combine(Channel.from(1))

BEDTOOLS_GENOMECOV (
    ch_genomecov_bam,
    [],
    'bedGraph'
)
```

I often go to refer to the tests about how to use a module, and we've hacked away the patterns just to test the functionality, rather than add some usage examples that can function as integration tests for new version releases.
