### ISSUE TITLE
Display nf-core/configs Institutions documentation on website

### ISSUE THREAD

**Issue by maxulysse** [nf-core/website#229]
It would be nice if we can have Institutions specific documentation on the nf-co.re website.
Would be much clearer for new users from Institutions to understand nf-core pipelines and configs if everything is in the same place.

**Comment by ewels** [comment]
Suggestion:

* https://nf-co.re/configs
    * https://github.com/nf-core/configs/blob/master/README.md
* https://nf-co.re/configs/PROFILE
    * https://github.com/nf-core/configs/blob/master/docs/PROFILE.md
* https://nf-co.re/configs/PROFILE/PIPELINE
    * https://github.com/nf-core/configs/blob/master/docs/pipeline/PIPELINE/PROFILE.md

Note the inversion of `PIPELINE` / `PROFILE` in the website URL. This is so that it follows a more intuitive hierarchy for the user from the institution (I think the opposite is true when writing the docs, so it still makes sense for the github repo as it is).

Do we want to break up the main readme file at all? Have separate files for how to contribute and keep the main readme much more low-level for new users? Ping @drpatelh.

Need to think about how to build the navigation for this on the website. I guess we should link to it from _Usage_ in the nav.

Phil

**Comment by jfy133** [comment]
it would be also nice to give 'reviewing guidelines' like for modules. Makes it much easier to review to get basic stuff right if there is a short/terse version of the guidelines +1

**Comment by mashehu** [comment]
that's a different issue I think, would be added to `/docs/` this is more about displaying the configs we have on the website.

**Comment by jfy133** [comment]
True, sorry. That's a copy-paste from the the now-closed configs docs PR, we have no guidelines yet and at the time I thought it made sense to add them to the README

**Comment by lukbut** [comment]
@ewels @ewels It looks like "Usage" is no longer in the navigation bar - maybe should we nest this under "Tools"?

**Comment by lukbut** [comment]
@mashehu Thanks - so is this ticket partially implemented then?

**Comment by lukbut** [comment]
Thanks let me take a look @mashehu

**Comment by lukbut** [comment]
I can see the new website was written in J$ - not my area of expertise 2bh. Will find another task which suits better.
